"""add mitre_techniques to threats

Revision ID: 9c3a66249557
Revises: f346e4bb48a1
Create Date: 2026-10-03 13:55:42.677746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9c3a66249557'
down_revision: Union[str, None] = 'f346e4bb48a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('threats', sa.Column('mitre_techniques', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'[]'::jsonb")))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('threats', 'mitre_techniques')
    # ### end Alembic commands ###
