"""add dedup columns

Revision ID: e942cee800a4
Revises: ed101b0d76be
Create Date: 2026-10-03 13:24:17.204306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e942cee800a4'
down_revision: Union[str, None] = 'ed101b0d76be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('dedup_hash', sa.String(length=64), nullable=False))
    op.create_index(op.f('ix_events_dedup_hash'), 'events', ['dedup_hash'], unique=True)
    op.add_column('threats', sa.Column('dedup_key', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_threats_dedup_key'), 'threats', ['dedup_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_threats_dedup_key'), table_name='threats')
    op.drop_column('threats', 'dedup_key')
    op.drop_index(op.f('ix_events_dedup_hash'), table_name='events')
    op.drop_column('events', 'dedup_hash')
    # ### end Alembic commands ###
