"""initial schema

Revision ID: ed101b0d76be
Revises: 
Create Date: 2026-10-03 13:20:45.068827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ed101b0d76be'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('source_ip', sa.String(length=45), nullable=True),
    sa.Column('source_port', sa.Integer(), nullable=True),
    sa.Column('dest_ip', sa.String(length=45), nullable=True),
    sa.Column('dest_port', sa.Integer(), nullable=True),
    sa.Column('user', sa.String(length=128), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('raw', sa.Text(), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_dest_ip'), 'events', ['dest_ip'], unique=False)
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_index(op.f('ix_events_severity'), 'events', ['severity'], unique=False)
    op.create_index(op.f('ix_events_source_ip'), 'events', ['source_ip'], unique=False)
    op.create_index(op.f('ix_events_ts'), 'events', ['ts'], unique=False)
    op.create_table('scans',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('target_ip', sa.String(length=45), nullable=False),
    sa.Column('scan_type', sa.String(length=32), nullable=False),
    sa.Column('open_ports', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('services', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scans_target_ip'), 'scans', ['target_ip'], unique=False)
    op.create_index(op.f('ix_scans_ts'), 'scans', ['ts'], unique=False)
    op.create_table('threats',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rule', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('source_ip', sa.String(length=45), nullable=True),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threats_rule'), 'threats', ['rule'], unique=False)
    op.create_index(op.f('ix_threats_severity'), 'threats', ['severity'], unique=False)
    op.create_index(op.f('ix_threats_source_ip'), 'threats', ['source_ip'], unique=False)
    op.create_index(op.f('ix_threats_ts'), 'threats', ['ts'], unique=False)
    op.create_table('threat_events',
    sa.Column('threat_id', sa.BigInteger(), nullable=False),
    sa.Column('event_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['threat_id'], ['threats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('threat_id', 'event_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('threat_events')
    op.drop_index(op.f('ix_threats_ts'), table_name='threats')
    op.drop_index(op.f('ix_threats_source_ip'), table_name='threats')
    op.drop_index(op.f('ix_threats_severity'), table_name='threats')
    op.drop_index(op.f('ix_threats_rule'), table_name='threats')
    op.drop_table('threats')
    op.drop_index(op.f('ix_scans_ts'), table_name='scans')
    op.drop_index(op.f('ix_scans_target_ip'), table_name='scans')
    op.drop_table('scans')
    op.drop_index(op.f('ix_events_ts'), table_name='events')
    op.drop_index(op.f('ix_events_source_ip'), table_name='events')
    op.drop_index(op.f('ix_events_severity'), table_name='events')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_index(op.f('ix_events_dest_ip'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
