"""add scan_audit

Revision ID: f346e4bb48a1
Revises: 7baa0634c357
Create Date: 2026-10-03 13:53:14.911269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f346e4bb48a1'
down_revision: Union[str, None] = '7baa0634c357'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scan_audit',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('requester', sa.String(length=64), nullable=False),
    sa.Column('target_ip', sa.String(length=45), nullable=False),
    sa.Column('ports_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('allowed', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('scan_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_audit_requester'), 'scan_audit', ['requester'], unique=False)
    op.create_index(op.f('ix_scan_audit_target_ip'), 'scan_audit', ['target_ip'], unique=False)
    op.create_index(op.f('ix_scan_audit_ts'), 'scan_audit', ['ts'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scan_audit_ts'), table_name='scan_audit')
    op.drop_index(op.f('ix_scan_audit_target_ip'), table_name='scan_audit')
    op.drop_index(op.f('ix_scan_audit_requester'), table_name='scan_audit')
    op.drop_table('scan_audit')
    # ### end Alembic commands ###
